### PR TITLE
fix(amqp-twin): Remove unnecessary link-detach handlers in Twin Client (fix #221 part deux)

### LINKED ISSUE #221: Device client fails on disconnect using AMQP/AMQP-WS (using NoRetry policy)
# Context
- **OS and version used:** Windows 10, Ubuntu 16.4... -->
- **Node.js version:** 7.10, 6.11
- **npm version:** 4.2
- **list of installed packages:** <VERSION> <!-- in a command prompt, from the directory containing your code: npm list 
"azure-iot-common": "^1.3.0",
    "azure-iot-device": "^1.3.0",
    "azure-iot-device-amqp": "^1.3.0",
    "azure-iot-device-mqtt": "^1.3.0",
    "color": "^3.0.0",
    "colors": "^1.1.2"

# Description of the issue:
Device client fails on disconnect using AMQP/AMQP-WS

# Code sample exhibiting the issue:
```javascript
'use strict';

require('colors');
var DeviceClient = require('azure-iot-device').Client;
var Message = require('azure-iot-common').Message;;
var DeviceProtocol;
var connectionString = 'XXXXX';
var messageCount = 0;
var messageSentCount = 0;
if (process.argv.length !== 3) {
    console.log("Usage: node app [-amqp | -amqpws | -mqtt | -mqttws]".yellow);
    return;
}

console.log();

switch (process.argv[2].toLowerCase()) {
    case "-amqp":
    case "amqp":
        console.log('Using AMQP'.green);
        DeviceProtocol = require('azure-iot-device-amqp').Amqp;
        break;
    case "-amqpws":
    case "amqpws":
        console.log('Using AMQP-WS'.green);
        DeviceProtocol = require('azure-iot-device-amqp').AmqpWs;
        break;
    case "-mqtt":
    case "mqtt":
        console.log('Using MQTT'.green);
        DeviceProtocol = require('azure-iot-device-mqtt').Mqtt;
        break;
    case "-mqttws":
    case "mqttws":
        console.log('Using MQTT-WS'.green);
        DeviceProtocol = require('azure-iot-device-mqtt').MqttWs;
        break;
    default:
        console.log('Unsupported protocol'.red);
        console.log("Usage: node app [-amqp | -amqpws | -mqtt | -mqttws]".yellow);
        break;

}

var deviceClient = DeviceClient.fromConnectionString(connectionString, DeviceProtocol);
// Disable retry policy
let NoRetry = require('azure-iot-common').NoRetry;
deviceClient.setRetryPolicy(new NoRetry());

deviceClient.open(function (err, transport) {
    if (err) {
        console.log('ERROR: '.red + err.message.red);
        process.abort();
    }
    else {
        console.log('AZURE IoT: Connected'.green);
        deviceClient.on('disconnect', function () {
            console.log('AZURE IoT: Disconnected'.bgGreen.white);
        });
        deviceClient.on('error', function (err) {
            console.log('AZURE IoT: Error: '.red + err.message.red);
        });
        deviceClient.getTwin(function (err, twin) {
            if (err) {
                console.log('AZURE IoT: Could not get twin: '.red + err.message.red);
            }
            else {
                console.log("AZURE IoT: Device twin is ready".green);
                twin.on('properties.desired', function (desiredChange) {
                    console.log("AZURE IoT: Received new state".green);
                    console.log("");
                    sendEvents();
                });
            }
        });
    }
});

function sendEvents() {

    setInterval(function () {
        messageCount++;
        var message = new Message(JSON.stringify({ dt: new Date(), messageCount: messageCount }));
        deviceClient.sendEvent(message, function (err) {
            messageSentCount ++ ;
            if (err) {
                let m = 'Unable to send message to to Azure IoT Hub  ' + messageSentCount + '/(' + messageCount + ')';
                console.log(m.red);
            }
            else {
                let m = 'Event has been sent to Azure IoT Hub  ' + messageSentCount + '/(' + messageCount + ')';
                console.log(m.green);
            }
            
        });
    }, 5000);

}
```
# Reproduce issue
1. Open a console (don't rurn in VS Code)
2. RUN: npm i azure-iot-common@1.3.0 azure-iot-device@1.3.0 azure-iot-device-amqp@1.3.0 azure-iot-device-mqtt@1.3.0 colors@1.1.2
3. Type:
```
npm app amqp
```
4. Disable wireless network adapter

# Console log of the issue:

```bash
λ node app.js amqpws

Using AMQP-WS
AZURE IoT: Connected
AZURE IoT: Device twin is ready
AZURE IoT: Received new state

Event has been sent to Azure IoT Hub  1/(1)
Unable to send message to to Azure IoT Hub  2/(5)
Unable to send message to to Azure IoT Hub  3/(5)
Unable to send message to to Azure IoT Hub  4/(5)
Unable to send message to to Azure IoT Hub  5/(5)
AZURE IoT: Disconnected
C:\temp\deviceConnectivityTest\node_modules\azure-iot-amqp-base\lib\amqp.js:109
                        callback();
                        ^

TypeError: callback is not a function
    at constructor.amqpError (C:\temp\deviceConnectivityTest\node_modules\azure-iot-amqp-base\lib\amqp.js:109:25)
    at constructor.handle (C:\temp\deviceConnectivityTest\node_modules\machina\lib\machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (C:\temp\deviceConnectivityTest\node_modules\machina\lib\machina.js:466:63)
    at constructor.<anonymous> (C:\temp\deviceConnectivityTest\node_modules\machina\lib\machina.js:702:17)
    at C:\temp\deviceConnectivityTest\node_modules\machina\node_modules\lodash\index.js:2874:23
    at C:\temp\deviceConnectivityTest\node_modules\machina\node_modules\lodash\index.js:3049:15
    at Function.<anonymous> (C:\temp\deviceConnectivityTest\node_modules\machina\node_modules\lodash\index.js:3346:13)
    at constructor.processQueue (C:\temp\deviceConnectivityTest\node_modules\machina\lib\machina.js:701:6)
    at constructor.Fsm.(anonymous function) [as processQueue] (C:\temp\deviceConnectivityTest\node_modules\machina\lib\machina.js:466:63)
    at constructor.transition (C:\temp\deviceConnectivityTest\node_modules\machina\lib\machina.js:661:12)
    at constructor.Fsm.(anonymous function) [as transition] (C:\temp\deviceConnectivityTest\node_modules\machina\lib\machina.js:466:63)
    at C:\temp\deviceConnectivityTest\node_modules\azure-iot-amqp-base\lib\amqp.js:366:48
    at disconnect (C:\temp\deviceConnectivityTest\node_modules\azure-iot-amqp-base\lib\amqp.js:319:33)
    at C:\temp\deviceConnectivityTest\node_modules\azure-iot-amqp-base\lib\amqp.js:363:33
    at C:\temp\deviceConnectivityTest\node_modules\async\dist\async.js:473:16
    at iteratorCallback (C:\temp\deviceConnectivityTest\node_modules\async\dist\async.js:1050:13)
```

### PR DESCRIPTION
**Pull request by pierreca**
# Related issue
#221

# Description of the problem
When a connection is lost the link are forceDetached which makes the amqp10 library emit a `detached` event on the link. The `AmqpTwinClient` class used to listen for these events (even though the link lifecycle is managed by the `Amqp` base class) and try to trigger a proper `detach` operation, which tried to write on a socket that is already disconnected, leading to a second (unnecessary) error.

# Description of the solution
Remove the link detached handlers. errors are still handled and bubbled up with other events so it seems these were left erroneously after some refactoring in the Amqp codebase.

Also using this PR to fix a couple of tests and reactivate the disconnection tests for AMQP (the retry tests will come next with more refactoring of the Twin stack)

### CODE REVIEW

File: device/transport/amqp/src/amqp_twin_client.ts [hunk 1]
```diff
@@ -221,13 +214,6 @@ export class AmqpTwinClient extends EventEmitter {
             this._fsm.deferUntilTransition('detached');
             this._fsm.transition('detaching');
           },
-          handleLinkDetach: (detachObject) => {
```
Comment (anthonyvercolano) [inline device/transport/amqp/src/amqp_twin_client.ts]: >handleLinkDetach: (detachObject) => { [](start = 10, length = 37)

While I'm trying to recall my thinking here,  The twin client upon receiving a detach, for ONE of the two links that created to perform twin communication, will try to close the other.  As written I don't believe it has a way to determine what the other is.  (If original detach occurs on the upstream link, I don't recall whether the detach on handler can determine that it was the upstream.  Consequently, it tries to kill both.  Are you saying the base amqp client will automagically detach both of these links.?

File: device/transport/amqp/src/amqp_twin_client.ts [hunk 2]
```diff
@@ -92,11 +92,6 @@ export class AmqpTwinClient extends EventEmitter {
             debug('_handleError: error is: ' + err);
             this.emit(AmqpTwinClient.errorEvent, translateError('received an error from the amqp transport: ', err));
           },
-          handleLinkDetach: (detachObject: any) => {
-            if (detachObject && detachObject.error) {
-              this.emit(AmqpTwinClient.errorEvent, translateError('received an error from the amqp transport: ', detachObject.error));
-            }
-          },
```
Comment (anthonyvercolano) [inline device/transport/amqp/src/amqp_twin_client.ts]: I'm thinking I just didn't put this in there for grins.  At least at the time that this was originally written, a detach bubbled up from below wouldn't necessary cause an error event to be emitted.  The upper clients are going to need those, yes?

Comment (pierreca) [reply device/transport/amqp/src/amqp_twin_client.ts]: the base layer takes care of caching and managing link states

---
In reply to: [167288747](https://github.com/Azure/azure-iot-sdk-node/pull/228#discussion_r167288747) [](ancestors = 167288747)

File: device/transport/amqp/src/amqp_twin_client.ts (hunk 1 above)
Comment (pierreca) [reply device/transport/amqp/src/amqp_twin_client.ts]: yes

---
In reply to: [167287836](https://github.com/Azure/azure-iot-sdk-node/pull/228#discussion_r167287836) [](ancestors = 167287836)

Comment (pierreca) [reply device/transport/amqp/src/amqp_twin_client.ts]: and for the record all the e2e tests (including disconnection and detach of the links) pass with this modification.

---
In reply to: [167311755](https://github.com/Azure/azure-iot-sdk-node/pull/228#discussion_r167311755) [](ancestors = 167311755,167287836)
