### PR TITLE
fix(azure-iot-mqtt-base): avoid calling mqtt.js functions on undefined mqttClient

### LINKED ISSUE #931: UnhandledPromiseRejectionWarning 'Cannot read property 'removeAllListeners' of undefined error' when using X.509 register in a promise.
# Context

- Node.js version v14.15.0
-  "dependencies": {
    "azure-iot-device": "^1.17.3",
    "azure-iot-device-amqp": "^1.13.3",
    "azure-iot-device-mqtt": "^1.15.3",
    "azure-iot-provisioning-device": "^1.8.7",
    "azure-iot-provisioning-device-mqtt": "^1.7.7",
    "azure-iot-provisioning-device-amqp": "^1.8.7",
    "azure-iot-security-x509": "^1.7.7",
    "azure-iot-security-symmetric-key": "^1.7.7",
    "rhea": "^1.0.24"
  }

## Description of the issue

When using the X.509 provisioning with an incorrect certificate file content, and using it in a promise node construction, an UnhandledPromiseRejectionWarning 'Cannot read property 'removeAllListeners' of undefined error' is thrown and can not be catched. This kills the node process. '[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)' catch doesn't seem to be correctly inplemented. in the register function. 

## Code sample exhibiting the issue

```
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

'use strict';

var iotHubTransport = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').Client;
var Message = require('azure-iot-device').Message;

var fs = require('fs');
// You can change the following using statement if you would like to try another protocol.
var Transport = require('azure-iot-provisioning-device-mqtt').Mqtt;
// var Transport = require('azure-iot-provisioning-device-amqp').Amqp;
// var Transport = require('azure-iot-provisioning-device-amqp').AmqpWs;
// var Transport = require('azure-iot-provisioning-device-http').Http;
// var Transport = require('azure-iot-provisioning-device-mqtt').MqttWs;

var X509Security = require('azure-iot-security-x509').X509Security;
var ProvisioningDeviceClient = require('azure-iot-provisioning-device').ProvisioningDeviceClient;

var provisioningHost = 'global.azure-devices-provisioning.net';
var idScope = '<...>';
var registrationId = '<...>';
var deviceCert = {
  cert: 'anything here as long as it is not a correct X.509 cert',
  key: 'anything here as long as it is not a correct X.509 key'
};

var transport = new Transport();
var securityClient = new X509Security(registrationId, deviceCert);
var deviceClient = ProvisioningDeviceClient.create(provisioningHost, idScope, transport, securityClient);

// Register the device.  Do not force a re-registration.
function register() {
  // Return a promise to enable retry
  return new Promise((resolve,reject) => {
    deviceClient.register().then( function(result) {
      if (err) {
        console.log("error registering device: " + err);
      } else {
        console.log('registration succeeded');
        console.log('assigned hub=' + result.assignedHub);
        console.log('deviceId=' + result.deviceId);
        var connectionString = 'HostName=' + result.assignedHub + ';DeviceId=' + result.deviceId + ';x509=true';
        var hubClient = Client.fromConnectionString(connectionString, iotHubTransport);
        hubClient.setOptions(deviceCert);
        hubClient.open(function(err) {
          if (err) {
            console.error('Failure opening iothub connection: ' + err.message);
          } else {
            console.log('Client connected');
            var message = new Message('Hello world');
            hubClient.sendEvent(message, function(err, res) {
              if (err) console.log('send error: ' + err.toString());
              if (res) console.log('send status: ' + res.constructor.name);
              process.exit(1);
            });
          }
        });
      }
    }).catch( function(err) {
      // Handle error
      console.log('Error: ' + err);
      reject(err);
    });
  })
}

register().catch( function(err) {
  // Handle error
  console.log('Error: ' + err);
});
```

## Console log of the issue
```
C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples>node register_x509.js
Error: Error: error:0909006C:PEM routines:get_name:no start line
Error: Error: error:0909006C:PEM routines:get_name:no start line
C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:271
        this._mqttClient.removeAllListeners();
                         ^

TypeError: Cannot read property 'removeAllListeners' of undefined
    at MqttBase._disconnectClient (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:271:26)
    at constructor._onEnter (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:116:31)
    at constructor.transition (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\machina\lib\machina.js:653:28)
    at constructor.Fsm.<computed> [as transition] (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\machina\lib\machina.js:466:63)
    at constructor.disconnect (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:75:36)
    at constructor.handle (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\machina\lib\machina.js:613:25)
    at constructor.Fsm.<computed> [as handle] (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\machina\lib\machina.js:466:63)
    at MqttBase.disconnect (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:164:19)
    at disconnect (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\azure-iot-provisioning-device-mqtt\lib\mqtt.js:328:29)
    at Mqtt._disconnect (C:\Users\<user>\Documents\GitHub\azure-iot-sdk-node\provisioning\device\samples\node_modules\azure-iot-provisioning-device-mqtt\lib\mqtt.js:347:13)
```

### PR DESCRIPTION
**Pull request by vishnureddy17**
fix #931

If `MqttBase` is in the `connecting` state and a state transition to `disconnecting` is initiated before `_mqttClient` is assigned a value, `removeAllListeners()` gets called on `undefined`, which causes a `TypeError` to be thrown. This PR fixes that problem.

### CODE REVIEW

File: common/transport/mqtt/test/_mqtt_base_test.js [hunk 1]
```diff
@@ -1,89 +1,112 @@
...
+var should = require("chai").should;
+var sinon = require("sinon");
 
-var MqttBase = require('../dist/mqtt_base.js').MqttBase;
-var FakeMqtt = require('./_fake_mqtt.js').FakeMqtt;
-var PubFakeMqtt = require('./_fake_mqtt.js').PubFakeMqtt;
-var PubACKTwiceFakeMqtt = require('./_fake_mqtt.js').PubACKTwiceFakeMqtt;
-var ErrorFakeMqtt = require('./_fake_mqtt.js').ErrorFakeMqtt;
-var errors = require('azure-iot-common').errors;
+var MqttBase = require("../dist/mqtt_base.js").MqttBase;
```
Comment (YoDaMa) [inline common/transport/mqtt/test/_mqtt_base_test.js:11]: curious about the change to double quotes. Is that our style standard?

**Comment by YoDaMa** [comment]
could you let me know if the formatting changes made with regards to single to double quotes are legitimate. I don't see that style enforced in the code.

**Comment by YoDaMa** [comment]
> could you let me know if the formatting changes made with regards to single to double quotes are legitimate. I don't see that style enforced in the code.

once you do this if you could separate the reformatting from adding the test so I can see which part of the test code you're changing. A good way to do this is to `git reset master` the commit the reformatting, feature, and tests in three distinct commits.

File: common/transport/mqtt/test/_mqtt_base_test.js (hunk 1 above)
Comment (vishnureddy17) [reply common/transport/mqtt/test/_mqtt_base_test.js:11]: Whoops. I think my formatter did that when I saved.

**Comment by vishnureddy17** [comment]
@YoDaMa I undid the stuff my formatter messed with. Sorry about that.

**Comment by YoDaMa** [comment]
this might fix the problem but let's make a note that our error handling in promises is broken, because that still appears to be the case. We should keep that in mind.

**Review by YoDaMa — APPROVED** [review]
